export const  links = {
    resumeLink: "https://drive.google.com/file/d/15V_I5zW-iQ8eYWvtQEmi6sZ-6DgWGvya/view",
    githubLink:"https://github.com/SubramanyaKS",
    linkedinLink: "https://www.linkedin.com/in/subramanyakshebbar/",
    youtubeLink:"https://www.youtube.com/@subramanyakshebbar/",
    twitterLink: "https://twitter.com/subbukshebbar",
    instagramLink:"",
    facebookLink:"https://www.facebook.com/profile.php?id=100070944345090",
    gmailLink:"mailto:subramanyaks22@gmail.com",
}
export const skillImage={
    c:"https://img.icons8.com/color/48/000000/c-programming.png",
    java:"https://img.icons8.com/color/48/000000/java-coffee-cup-logo--v1.png",
    python:"https://img.icons8.com/color/48/000000/python--v1.png",
    mysql:"https://img.icons8.com/color/60/000000/mysql-logo.png",
    mongodb:"https://img.icons8.com/color/48/000000/mongodb.png",
    postgres:"https://img.icons8.com/color/48/postgreesql.png",
    css:"https://img.icons8.com/color/48/000000/css3.png",
    html:"https://img.icons8.com/color/48/000000/html-5--v1.png",
    javascript:"https://img.icons8.com/color/48/000000/javascript--v1.png",
    react:"https://img.icons8.com/ultraviolet/48/000000/react--v1.png",
    vscode:"https://img.icons8.com/color/48/000000/visual-studio-code-2019.png",
    eclipse:"https://img.icons8.com/office/40/null/java-eclipse.png",
    node:"https://img.icons8.com/color/48/000000/nodejs.png",
    bootstrap:"https://img.icons8.com/color/48/000000/bootstrap.png",
    django:"https://img.icons8.com/color/48/ffffff/django.png",
    flask:"https://img.icons8.com/nolan/64/flask.png",
    reactnative:"https://img.icons8.com/nolan/64/react-native.png",
    git: "https://img.icons8.com/color/48/000000/git.png",
    android: "https://img.icons8.com/color/48/000000/android-os.png",
    postman: "https://img.icons8.com/external-tal-revivo-color-tal-revivo/48/null/external-postman-is-the-only-complete-api-development-environment-logo-color-tal-revivo.png",
}

